# Generated by Django 3.1.5 on 2021-01-10 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='slag',
            new_name='slug',
        ),
    ]
