# Generated by Django 3.1.5 on 2021-01-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210111_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='descriptions',
            new_name='description',
        ),
    ]
